// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "aquaculture/models"

	mock "github.com/stretchr/testify/mock"
)

// ArticleRepository is an autogenerated mock type for the ArticleRepository type
type ArticleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: aReq
func (_m *ArticleRepository) Create(aReq models.ArticleRequest) (models.Article, error) {
	ret := _m.Called(aReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(models.ArticleRequest) (models.Article, error)); ok {
		return rf(aReq)
	}
	if rf, ok := ret.Get(0).(func(models.ArticleRequest) models.Article); ok {
		r0 = rf(aReq)
	} else {
		r0 = ret.Get(0).(models.Article)
	}

	if rf, ok := ret.Get(1).(func(models.ArticleRequest) error); ok {
		r1 = rf(aReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *ArticleRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *ArticleRepository) GetAll() ([]models.Article, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Article
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Article, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Article); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Article)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *ArticleRepository) GetByID(id string) (models.Article, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Article, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Article); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Article)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: aReq, id
func (_m *ArticleRepository) Update(aReq models.ArticleRequest, id string) (models.Article, error) {
	ret := _m.Called(aReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(models.ArticleRequest, string) (models.Article, error)); ok {
		return rf(aReq, id)
	}
	if rf, ok := ret.Get(0).(func(models.ArticleRequest, string) models.Article); ok {
		r0 = rf(aReq, id)
	} else {
		r0 = ret.Get(0).(models.Article)
	}

	if rf, ok := ret.Get(1).(func(models.ArticleRequest, string) error); ok {
		r1 = rf(aReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewArticleRepository creates a new instance of ArticleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArticleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArticleRepository {
	mock := &ArticleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
