// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "aquaculture/models"

	mock "github.com/stretchr/testify/mock"
)

// FarmRepository is an autogenerated mock type for the FarmRepository type
type FarmRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: farmReq
func (_m *FarmRepository) Create(farmReq models.FarmRequest) (models.Farm, error) {
	ret := _m.Called(farmReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(models.FarmRequest) (models.Farm, error)); ok {
		return rf(farmReq)
	}
	if rf, ok := ret.Get(0).(func(models.FarmRequest) models.Farm); ok {
		r0 = rf(farmReq)
	} else {
		r0 = ret.Get(0).(models.Farm)
	}

	if rf, ok := ret.Get(1).(func(models.FarmRequest) error); ok {
		r1 = rf(farmReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *FarmRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *FarmRepository) GetAll() ([]models.Farm, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Farm, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Farm); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Farm)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *FarmRepository) GetByID(id string) (models.Farm, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Farm, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Farm); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Farm)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: farmReq, id
func (_m *FarmRepository) Update(farmReq models.FarmRequest, id string) (models.Farm, error) {
	ret := _m.Called(farmReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Farm
	var r1 error
	if rf, ok := ret.Get(0).(func(models.FarmRequest, string) (models.Farm, error)); ok {
		return rf(farmReq, id)
	}
	if rf, ok := ret.Get(0).(func(models.FarmRequest, string) models.Farm); ok {
		r0 = rf(farmReq, id)
	} else {
		r0 = ret.Get(0).(models.Farm)
	}

	if rf, ok := ret.Get(1).(func(models.FarmRequest, string) error); ok {
		r1 = rf(farmReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFarmRepository creates a new instance of FarmRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFarmRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FarmRepository {
	mock := &FarmRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
