// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "aquaculture/models"

	mock "github.com/stretchr/testify/mock"
)

// FarmTypeRepository is an autogenerated mock type for the FarmTypeRepository type
type FarmTypeRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ftReq
func (_m *FarmTypeRepository) Create(ftReq models.FarmTypeRequest) (models.FarmType, error) {
	ret := _m.Called(ftReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.FarmType
	var r1 error
	if rf, ok := ret.Get(0).(func(models.FarmTypeRequest) (models.FarmType, error)); ok {
		return rf(ftReq)
	}
	if rf, ok := ret.Get(0).(func(models.FarmTypeRequest) models.FarmType); ok {
		r0 = rf(ftReq)
	} else {
		r0 = ret.Get(0).(models.FarmType)
	}

	if rf, ok := ret.Get(1).(func(models.FarmTypeRequest) error); ok {
		r1 = rf(ftReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *FarmTypeRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *FarmTypeRepository) GetAll() ([]models.FarmType, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.FarmType
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.FarmType, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.FarmType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FarmType)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *FarmTypeRepository) GetByID(id string) (models.FarmType, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.FarmType
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.FarmType, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.FarmType); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.FarmType)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ftReq, id
func (_m *FarmTypeRepository) Update(ftReq models.FarmTypeRequest, id string) (models.FarmType, error) {
	ret := _m.Called(ftReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.FarmType
	var r1 error
	if rf, ok := ret.Get(0).(func(models.FarmTypeRequest, string) (models.FarmType, error)); ok {
		return rf(ftReq, id)
	}
	if rf, ok := ret.Get(0).(func(models.FarmTypeRequest, string) models.FarmType); ok {
		r0 = rf(ftReq, id)
	} else {
		r0 = ret.Get(0).(models.FarmType)
	}

	if rf, ok := ret.Get(1).(func(models.FarmTypeRequest, string) error); ok {
		r1 = rf(ftReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFarmTypeRepository creates a new instance of FarmTypeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFarmTypeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FarmTypeRepository {
	mock := &FarmTypeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
