// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "aquaculture/models"

	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: productReq
func (_m *ProductRepository) Create(productReq models.ProductRequest) (models.Product, error) {
	ret := _m.Called(productReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(models.ProductRequest) (models.Product, error)); ok {
		return rf(productReq)
	}
	if rf, ok := ret.Get(0).(func(models.ProductRequest) models.Product); ok {
		r0 = rf(productReq)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(models.ProductRequest) error); ok {
		r1 = rf(productReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *ProductRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *ProductRepository) GetAll() ([]models.Product, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Product, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *ProductRepository) GetByID(id string) (models.Product, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.Product); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: productReq, id
func (_m *ProductRepository) Update(productReq models.ProductRequest, id string) (models.Product, error) {
	ret := _m.Called(productReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(models.ProductRequest, string) (models.Product, error)); ok {
		return rf(productReq, id)
	}
	if rf, ok := ret.Get(0).(func(models.ProductRequest, string) models.Product); ok {
		r0 = rf(productReq, id)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(models.ProductRequest, string) error); ok {
		r1 = rf(productReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductRepository creates a new instance of ProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepository {
	mock := &ProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
