// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	models "aquaculture/models"

	mock "github.com/stretchr/testify/mock"
)

// TransactionDetailRepository is an autogenerated mock type for the TransactionDetailRepository type
type TransactionDetailRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: tdReq
func (_m *TransactionDetailRepository) Create(tdReq models.TransactionDetailRequest) (models.TransactionDetail, error) {
	ret := _m.Called(tdReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.TransactionDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(models.TransactionDetailRequest) (models.TransactionDetail, error)); ok {
		return rf(tdReq)
	}
	if rf, ok := ret.Get(0).(func(models.TransactionDetailRequest) models.TransactionDetail); ok {
		r0 = rf(tdReq)
	} else {
		r0 = ret.Get(0).(models.TransactionDetail)
	}

	if rf, ok := ret.Get(1).(func(models.TransactionDetailRequest) error); ok {
		r1 = rf(tdReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *TransactionDetailRepository) GetAll() ([]models.TransactionDetail, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.TransactionDetail
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.TransactionDetail, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.TransactionDetail); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TransactionDetail)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *TransactionDetailRepository) GetByID(id string) (models.TransactionDetail, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.TransactionDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.TransactionDetail, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.TransactionDetail); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.TransactionDetail)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: tdReq, id
func (_m *TransactionDetailRepository) Update(tdReq models.TransactionDetailRequest, id string) (models.TransactionDetail, error) {
	ret := _m.Called(tdReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.TransactionDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(models.TransactionDetailRequest, string) (models.TransactionDetail, error)); ok {
		return rf(tdReq, id)
	}
	if rf, ok := ret.Get(0).(func(models.TransactionDetailRequest, string) models.TransactionDetail); ok {
		r0 = rf(tdReq, id)
	} else {
		r0 = ret.Get(0).(models.TransactionDetail)
	}

	if rf, ok := ret.Get(1).(func(models.TransactionDetailRequest, string) error); ok {
		r1 = rf(tdReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionDetailRepository creates a new instance of TransactionDetailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionDetailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionDetailRepository {
	mock := &TransactionDetailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
